version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - ../Exchangeapp_backend:/app
    ports:
      - "3000:3000"
    command: go run main.go
    environment:
      - GIN_MODE=release
    restart: unless-stopped

networks:
  default:
    name: currency-forum-network
